language: php
php:
  - 5.3.2
  - 5.3
  - 5.4

script:
 - phpunit --coverage-text

before_script:
 - pyrus install -f http://download.pear.php.net/package/PEAR-1.9.4.tgz
 - pyrus install -f -p pyrus/Pyrus_Developer
 - pyrus install -f pear2.php.net/PEAR2_Exception
 - wget http://getcomposer.org/composer.phar
 - php -r "var_dump(filter_var('http://pear.symfony-project.com/', FILTER_VALIDATE_URL));"
 - php composer.phar install